apiVersion: v1
kind: Deployment
metadata:
  labels:
    test: readiness
  name: readiness-deployment
spec:
  replicas: 3
  selector:
    matchlables:
      app: readiness-test
  template:
    meta-data:
      labels:
        app: readiness-test
  containers:
  - name: readiness
    image: gcr.io/google-samples/hello-app:1.0
    ports:
    - containerPort: 8080
      protocol: TCP
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - sleep 60; touch /tmp/healthy; sleep (60 + RANDOM % 120) ; rm -rf /tmp/healthy
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 300
      periodSeconds: 5
apiVersion: v1
kind: Service
metadata:
  name: readiness-svc
spec:
  type: ClusterIP
  selector:
    matchlables:
      app: readiness-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080